server.port=8888
spring.application.name=config-server

# Use a local folder as the config repo (simplest for local dev)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config-repo